# Generated by Django 5.2.12 on 2026-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Админ"),
                            ("manager", "Менеджер"),
                            ("user", "Пользователь"),
                            ("guest", "Гость"),
                        ],
                        default="user",
                        max_length=7,
                        unique=True,
                        verbose_name="роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
    ]
