# Generated by Django 5.2.12 on 2026-03-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0001_initial"),
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRolesRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_all_permission", models.BooleanField(default=False)),
                ("create_permission", models.BooleanField(default=False)),
                ("update_all_permission", models.BooleanField(default=False)),
                ("delete_all_permission", models.BooleanField(default=False)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elements.element",
                        verbose_name="элемент",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Право доступа",
                "verbose_name_plural": "Права доступа",
            },
        ),
    ]
