# Generated by Django 5.2.12 on 2026-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0002_alter_element_name"),
        ("users", "0004_accessrolesrules"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accessrolesrules",
            constraint=models.UniqueConstraint(
                fields=("role", "element"), name="unique_role_element"
            ),
        ),
    ]
