# Generated by Django 5.2.12 on 2026-03-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0002_alter_element_name"),
        ("users", "0005_accessrolesrules_unique_role_element"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrolesrules",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elements.element",
                verbose_name="Элемент",
            ),
        ),
        migrations.AlterField(
            model_name="accessrolesrules",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.role",
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Админ"),
                    ("manager", "Менеджер"),
                    ("user", "Пользователь"),
                    ("guest", "Гость"),
                ],
                default="user",
                max_length=7,
                unique=True,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
    ]
