# Generated by Django 5.2.12 on 2026-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("users", "Пользователи"),
                            ("products", "Товары"),
                            ("orders", "Заказы"),
                            ("permissions", "Права доступа"),
                        ],
                        max_length=11,
                        unique=True,
                        verbose_name="Элемент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент",
                "verbose_name_plural": "Элементы",
            },
        ),
    ]
