# Generated by Django 5.2.12 on 2026-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="name",
            field=models.CharField(
                choices=[
                    ("users", "Пользователи"),
                    ("products", "Товары"),
                    ("orders", "Заказы"),
                    ("roles", "Роли"),
                    ("permissions", "Права доступа"),
                    ("elements", "Элементы"),
                ],
                max_length=11,
                unique=True,
                verbose_name="Элемент",
            ),
        ),
    ]
